import {
  TOOTH_STATE,
  TOOTH_FACE_AFFECTION,
  type ITeethList,
  type TOOTH_FACE_AFFECTION_TYPE,
} from '@modules/appointment/types/teeth.type';

export const ARRAY_FACE_AFFECTIONS: TOOTH_FACE_AFFECTION_TYPE[] = [
  'healthy',
  'decay',
  'filling',
  'crown',
  'fracture',
  'sealant',
  'bridge',
  'implant',
  'abscess',
  'wear',
  'erosion',
  'stain',
  'chipped',
  'sensitive',
];

export const CONSTANTTEETHLIST: ITeethList = {
  permanent: {
    '1': [
      {
        tooth_number: 18,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 17,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 16,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 15,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 14,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 13,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 12,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 11,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 11 al 18
    '2': [
      {
        tooth_number: 21,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 22,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 23,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 24,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 25,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 26,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 27,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 28,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 21 al 28
    '3': [
      {
        tooth_number: 48,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 47,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 46,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 45,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 44,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 43,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 42,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 41,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 41 al 48
    '4': [
      {
        tooth_number: 31,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 32,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 33,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 34,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 35,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 36,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 37,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 38,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 31 al 38
  },
  temporary: {
    '5': [
      {
        tooth_number: 55,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 54,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 53,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 52,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 51,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 51 al 55
    '6': [
      {
        tooth_number: 61,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 62,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 63,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 64,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 65,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 61 al 65
    '7': [
      {
        tooth_number: 71,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 72,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 73,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 74,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 75,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 71 al 75
    '8': [
      {
        tooth_number: 85,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 84,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 83,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 82,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
      {
        tooth_number: 81,
        general_state: TOOTH_STATE.HEALTHY,
        palatina: TOOTH_FACE_AFFECTION.HEALTHY,
        distal: TOOTH_FACE_AFFECTION.HEALTHY,
        mesial: TOOTH_FACE_AFFECTION.HEALTHY,
        vestibular: TOOTH_FACE_AFFECTION.HEALTHY,
        oclusal: TOOTH_FACE_AFFECTION.HEALTHY,
      },
    ], // Dientes del 81 al 85
  },
};
